version: "3.3"
services:
  mealie:
    image: hkotel/mealie:omni-nightly
    restart: always
    ports:
      - "172.17.0.1:9925:3000"
    volumes:
      - ./data:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - BASE_URL=${BASE_URL}
      - DEFAULT_EMAIL=${ADMIN_EMAIL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_AUTH_STRATEGY=${SMTP_AUTH_STRATEGY}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
